[package]
name = "end"
version = "0.0.4"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "endian conversion"
license = "MIT OR Apache-2.0"
edition = "2018"

[lib]
name = "endian"

[dependencies]
num-traits = { version = "0.2.12", default-features = false }
